version: '3.8'

services:
  network_logger:
    build: ./go_service
    volumes:
      - ./data:/app/data
    restart: always

  ai_model:
    build: ./ai_service
    volumes:
      - ./data:/app/data
    depends_on:
      - network_logger
    restart: always
